# What are AnVIL Champions?

An AnVIL Champion serves as a point person within a community (institution, consortium, research group, geographic region, etc.) who can be a local resource for people interested in using AnVIL. AnVIL Champions help people in their community to understand the benefits of AnVIL, get started using the platform, and find appropriate resources for learning more. They also help AnVIL better meet the needs of their community by communicating feedback to the AnVIL team.

<iframe width="560" height="315" src="https://www.youtube.com/embed/PptqHHXke54?si=tnnM0Z2JGSOgEJRD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

**An AnVIL Champion does not need to be an expert on all things AnVIL!** Primarily, they need to be able to direct people to appropriate resources for finding help, and to serve as a local knowledge store for any community-specific considerations. Examples of ways in which AnVIL Champions can help their community include:

- [Helping new users get started](#onboard): Help new AnVIL users think through setting up their teams, and direct them to AnVIL's Getting Started resources
  - Also provide advice about community-specific considerations, such as explaining an institution’s preferred billing mechanism
- [Guiding users to resources for learning more](#learn): Help community members find and navigate to the broad collection of resources for learning more about how to use AnVIL for their specific needs
- [Pointing users towards support channels](#help): Help community members get answers to their specific questions by directing them towards existing channels for receiving help on AnVIL
- [Communicating feedback](#communicate): Gather feedback from your community and communicate it to the AnVIL team
  - Also guide community members to appropriate communication channels if they wish to provide feedback directly to the AnVIL team

::: {.reflection}
Here is what AnVIL Champions' interactions might look like:

Sam is an AnVIL Champion in a research consortium and works closely with an analyst, Alex. Alex messages Sam on Slack to ask about running a workflow on AnVIL. Sam responds by pointing to existing AnVIL tutorials and explains the consortium's billing preferences. Sam isn't an expert on workflows, and directs a few specific questions to the AnVIL team through [help.anvilproject.org](https://help.anvilproject.org).
:::

## What do you need to be an AnVIL Champion?

- Basic understanding of AnVIL
- Comfort with new technology
- Willingness to help new users

## Why be an AnVIL Champion?

- Targeted training opportunities
- Streamlined communication with support and developers
- Help your community
- CV / badge e.g. "Served as AnVIL Champion for Consortium X May 2024 - present"

