# Onboard New Users {#onboard}

Getting started on AnVIL can be a bit overwhelming. As an AnVIL Champion, you can help new users by:

## Discussing Team Configuration

There are several decisions that need to be made when setting up a new group on AnVIL. These can be challenging for new users because they are unfamiliar with the vocabulary and unclear on the implications of their decisions. As an AnVIL Champion, you can help by being familiar with the decisions faced by new users and helping people think through how to set up their team.

Here are some points that people will need to consider when setting up their group(s) on AnVIL:

- **Billing Account** -- What Google Billing Account will you use?  Note that a Billing Account is required to store data, conduct analysis, etc.
- **Cost Monitoring** -- Who will monitor spending?  Will this person be able to monitor daily/weekly?
- **Team Management** -- Who will oversee the onboarding and offboarding of members?  Will this person track the manifest of workspaces?
- **Data Access** -- Which datasets will you be generating or analyzing?  Do you already have access to these datasets?
- **Data Analysis** -- Which tools will you need to do your analysis?  Are these already Docker-ized / WDL-ized?

::: {.reflection}
If these are new to you, don't worry! The AnVIL team will train you.
:::

## Directing People to Resources

The [Getting Started on AnVIL](https://jhudatascience.org/AnVIL_Book_Getting_Started) book is a great resource for new users that walks them step-by-step through setting up their group.
See [Learn More](#learn) and [Get Help](#help) for additional resources.

## Explaining Community-Specific Considerations

Most communities will have some specific considerations that people should be aware of when working on AnVIL. As an AnVIL Champion, you can help by being the local expert on common questions and concerns for your community. These can include things like:

- **Preferred billing mechanism**: Do individual groups handle their own billing, or is there e.g. an institutional agreement with Google Cloud Platform or a third-party reseller?
- **Cost reporting requirements**: What, if any, reports need to be submitted, what information should they include, and what’s the easiest way to get that out of GCP? Is there someone who needs to be added to the Billing Account so that they can view the GCP spending reports?
- **Data and tools**: Where do people find and access the data and tools they need to carry out their research? If your community is centered around a particular type of data or field of research, then there may be some common datasets and analysis tools that will be broadly useful to members of the community. You can help your community by explaining where these are maintained, how to import them into AnVIL Workspaces, and where to look for help if they are having problems.
- **Security**: If your community regularly works with sensitive or protected data, you can help new users comply with security requirements by explaining common community practices and by connecting them with other members of the community who have dealt with similar concerns and may be able to give them guidance.

You don’t need to be able to answer every question that comes your way! Sharing your experience of getting started on AnVIL and your choices for setting up your team are a valuable starting point for new users. You can be incredibly helpful by being able to answer some of the most common questions that come up within your community, and by making sure your community members are aware of any local requirements for working with AnVIL.


