
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits).

&nbsp;
&nbsp;

<!-- Authors of AnVIL modules have been listed as Content Contributors, under "AnVIL instructions". -->

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor(s)|[Katherine Cox]|
|Lecturer(s)||
|Content Author(s)|| 
|Content Contributor(s)|[Ava Hoffman]|
|Content Editor(s)/Reviewer(s)|Frederick Tan, Javier Carpinteyro-Ponce, [Ava Hoffman], [Elizabeth Humphries], Natalie Kucher|
|Content Director(s)|Frederick Tan|
|Content Consultants||
|Acknowledgments||
|**Production**||
|Content Publisher(s)| Helped with publishing platform|
|Content Publishing Reviewer(s)| Reviewed overall content and aesthetics on publishing platform|
|**Technical**||
|Course Publishing Engineer(s)| Helped with the code for the technical aspects related to the specific course generation|
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Candace Savonen]|
|Package Developers ([ottrpal])|[John Muschelli], [Candace Savonen], [Carrie Wright]|
|**Art and Design**||
|Illustrator(s)| Created graphics for the course|
|Figure Artist(s)| Created figures/plots for course|
|Videographer(s)| Filmed videos|
|Videography Editor(s)| Edited film|
|Audiographer(s)| Recorded audio|
|Audiography Editor(s)| Edited audio recordings|
|**Funding**||
|Funder(s)| Institution/individual who funded course including grant number|
|Funding Staff| Staff members who help with funding|

&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```

<!-- Author information -->

[FirstName LastName]: link to personal website
[Allie Cliffe]: https://alliecliffe.com/
[Katherine Cox]: https://katherinecox.github.io/
[Ava Hoffman]: https://www.avahoffman.com/
[Elizabeth Humphries]: https://www.linkedin.com/in/elizabeth-humphries-61202a103/
[John Muschelli]: https://johnmuschelli.com/
[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/

<!-- Links -->

[ottrpal]: https://github.com/jhudsl/ottrpal

<!-- Fill out this table using these instructions: https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits

For JHU courses, You will need to add Ira as a credit:

|Content Publisher|[Ira Gooding]|
...
[Ira Gooding]: https://publichealth.jhu.edu/faculty/4130/ira-gooding
-->
