---
title: "AnVIL Champions"
date: "`r format(Sys.time(), '%B %d, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
description: A short booklet describing the AnVIL Champions initiative
favicon: assets/AnVIL_style/anvil_favicon.ico
---


# About this Book {-}

This "booklet" is part of a series of books for the Genomic Data Science Analysis, Visualization, and Informatics Lab-space (AnVIL) of the National Human Genome Research Institute (NHGRI). This short booklet explains what AnVIL Champions are and serves as a resource for AnVIL Champions as they support their community.

```{r, echo=FALSE, fig.alt="Two women sitting together with a laptop.", out.width = "80%", fig.align = 'center'}
ottrpal::include_slide("https://docs.google.com/presentation/d/1ZJI4mIqAR7_ircoYGk-8GZnZ3URDRcWpBFP6dbRL-9w/edit#slide=id.g115e284bdc2_0_0")
```

## Inspired by {- .unlisted}

The AnVIL Champions program is inspired by programs such as:

- [Center for Scientific Collaboration and Community Engagement (CSCCE)](https://cscce.org/resources/community-champions-programs),
- [Cyberinfrastructure Campus Champions Program](https://campuschampions.cyberinfrastructure.org/)
- [National Microbiome Data Collaborative Champions Program](https://microbiomedata.org/community/championsprogram/)
- [Nextflow Ambassadors](https://www.nextflow.io/ambassadors.html)
- [PREreview Champions Program](https://content.prereview.org/announcing-the-prereview-champions-program/)
- [rOpenSci Champions Program](https://ropensci.org/champions/)


## AnVIL Collection {-}

Learn more about AnVIL by visiting https://anvilproject.org or reading the [article in Cell Genomics](https://www.sciencedirect.com/science/article/pii/S2666979X21001063).

Please check out our full collection of AnVIL and related resources: https://hutchdatascience.org/AnVIL_Collection/

